### ISSUE TITLE
Are there higher resolution images?

### ISSUE THREAD

**Issue by marc-philipp-knechtle** [ajjimeno/icdar-task-b#1]
I noticed this competition dataset while reading `Image-based table recognition: data, model, and evaluation` and viewed some files with their corresponding annotation. But sadly the image resolution is very low. Is there any version of this dataset with a higher resolution?

Thanks in advance :)

**Comment by ajjimeno** [comment]
The only way is to obtain the image of the tables from the original articles, but it might be quite some work. Using the name of the image it should be possible to identify the document.

**Comment by marc-philipp-knechtle** [comment]
Alright, then I'll try integrating upscaling in my workflow ;) Thanks!
